name: niv

license: MIT

ghc-options:
    - -Wall
    - -Werror

dependencies:
    - base
    - text
    - mtl
    - unliftio

library:
    source-dirs:
        - src
    dependencies:
        - aeson
        - github
        - tasty
        - tasty-hunit
        - unordered-containers

executables:
    niv:
        source-dirs:
            - app
        main: Niv.main
        data-files:
            - nix/sources.nix
        dependencies:
            - aeson
            - aeson-pretty
            - bytestring
            - directory
            - filepath
            - github
            - hashable
            - file-embed
            - niv
            - optparse-applicative
            - process
            - string-qq
            - tasty
            - unordered-containers
