name: niv

license: MIT

ghc-options:
    - -Wall
    - -Werror

executable:
    main: app/Niv.hs
    dependencies:
        - base
        - hashable
        - file-embed
        - process
        - text
        - bytestring
        - aeson
        - aeson-pretty
        - directory
        - string-qq
        - filepath
        - github
        - mtl
        - optparse-applicative
        - unliftio
        - unordered-containers
    data-files:
        - nix/sources.nix
