name: "Test"
on:
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: ./script/test
